# -*- coding: utf-8 -*-
"""setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UEa6wN1ixKqzSy-JeNsyKLxKMdI0Co7e
"""

from setuptools import setup

setup(name='TheRealFufi',
      version='0.0.1',
      url="https://github.com/Gaianeve/gym-TheRealFufi",
      author="Gaia Bartoli",
      install_requires=install_requires=["gym==0.26.0", "pygame==2.1.0"],
)
